# Koyeb設定ファイル
services:
  - name: crossroid
    image: crossroid:latest
    ports:
      - port: 3000
        http:
          paths:
            - path: /
              pathType: Prefix
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "3000"
    # 環境変数はKoyebダッシュボードで設定してください
    # DISCORD_TOKEN: your_discord_bot_token
    # GROQ_API_KEY: your_groq_api_key (オプション)
